#!/bin/sh
set -e

staged_files="$(git diff --cached --name-only --diff-filter=ACMR)"

if [ -z "$staged_files" ]; then
  exit 0
fi

echo "$staged_files" | grep -E '^apps/web/' >/dev/null 2>&1 || exit 0

pnpm.cmd --filter @quiz-app/web lint
